
package lipid;

unit LipidScoreUnit;

// TODO Include here rules and queries to fulfill the practice requirements


// This is one example of rules that only prints the factorial combination of all pairs eliminating the A-A combination.
// !! TODO This rule does not include the lipid type, you shall add it.
// !! TODO Rule that states that the same lipid type with the same number of double bonds and a higher number of carbons should have a higher RT
// !! TODO
/*
rule "Score 1 for lipid pair with increasing RT and carbon count"
when
    $a1 : /annotations [$rt1 : rtMin, $carbonCount1 : lipid.getCarbonCount(), $doubleBondCount : lipid.getDoubleBondsCount()]
    $a2 : /annotations [this!= $a1, lipid.getDoubleBondsCount() == $doubleBondCount,
    rtMin > $rt1, lipid.getCarbonCount() > $carbonCount1]
then
    // in this case, the only change is the addition of the score, but the fact does not change so we do not break the principle of refractoriness
    $a1.addScore(1);
    $a2.addScore(1);
    // !! TODO ONLY FOR DEBUGGING
    System.out.println("Scored 1 for annotations: " + $a1 + " and " + $a2);
end
*/

// Rules 1-3: each rule adds a score of 1

// Rule 1: Same lipid type and double bonds, more carbons, higher RT

rule "Rule 1: Same type of lipid, same double bonds, more carbons, higher RT"
when
    $a1 : /annotations[
        $rt1 : rtMin,
        $lipidType1 : lipid.getLipidType(),
        $carbonCount1 : lipid.getCarbonCount(),
        $doublebondCount : lipid.getDoubleBondsCount()
    ]
    $a2 : /annotations[
        this != $a1,
        lipid.getLipidType() == $lipidType1,
        lipid.getDoubleBondsCount() == $doublebondCount,
        lipid.getCarbonCount() < $carbonCount1,
        rtMin < $rt1
    ]
then
    $a1.addScore(1);
    $a2.addScore(1);
    System.out.println("\nRule 1 passed: Anotations have same lipid type, same DBs, more carbons, higher RT."
    + "\n Add a score of +1 to both annotations: \n - " + $a1 + "\n - " + $a2);
end

// Rule 2: Same type and carbon count, fewer double bonds → higher RT
rule "Rule 2: same lipid type, same carbons, fewer double bonds → higher RT"
when
    $a1 : /annotations[
        $rt1 : rtMin,
        $lipidType1 : lipid.getLipidType(),
        $carbonCount1 : lipid.getCarbonCount(),
        $doublebondCount : lipid.getDoubleBondsCount()
    ]

    $a2 : /annotations[
        this != $a1,
        lipid.getLipidType() == $lipidType1,
        lipid.getCarbonCount() == $carbonCount1,
        lipid.getDoubleBondsCount() > $doublebondCount,
        rtMin < $rt1
    ]
then
    $a1.addScore(1);
    $a2.addScore(1);
    System.out.println("\nRule 2: Anotations have same lipid type, fewer DBs, same carbons, higher RT."
                                  + "\nAdd a score of +1 to both anotations:\n - " + $a1 + "\n - " + $a2);
end

// Rule 3: Different type, same carbon/double bonds, type elution order respected → higher RT
rule "Rule 3: Different lipid type (higher type rank), same double bonds, same carbons, higher retention time"
when
    $a1 : /annotations [
        $lipidType1 : lipid.getLipidType(),
        $doubleBondCount1 : lipid.getDoubleBondsCount(),
        $carbonCount1 : lipid.getCarbonCount(),
        $retentionTime1 : rtMin
    ]
    $a2 : /annotations [
        this != $a1,
        lipid.getLipidType() != $lipidType1,
        lipid.getDoubleBondsCount() == $doubleBondCount1,
        lipid.getCarbonCount() == $carbonCount1,
        rtMin < $retentionTime1
    ]
    eval($a1.getLipid().getLipidTypeRank() > $a2.getLipid().getLipidTypeRank())
then
    $a1.addScore(1);
    $a2.addScore(1);
    System.out.println("\nRule 3: Anotations have different lipid type (higher rank), same DBs, same carbons, higher RT."
            + "\nAdd a score of +1 to both anotations:\n - " + $a1 + "\n - " + $a2);
end

// !! TODO NEXT RULE: Negative evidence. If the RT follows the opposite order than the previous one, then the addScore should be -1.
// Rules 4-6: each rule adds a score of -1
// Rule 4: same type and double bonds, more carbons → but RT is lower ⇒ penalize
rule "Rule 4: Same lipid type, same double bonds, more carbons, lower retention time"
when
    $a1 : /annotations [
        $lipidType1 : lipid.getLipidType(),
        $doubleBondCount : lipid.getDoubleBondsCount(),
        $carbonCount1 : lipid.getCarbonCount(),
        $retentionTime1 : rtMin
    ]
    $a2 : /annotations [
        this != $a1,
        lipid.getLipidType() == $lipidType1,
        lipid.getDoubleBondsCount() == $doubleBondCount,
        lipid.getCarbonCount() < $carbonCount1,
        rtMin > $retentionTime1
    ]
then
    $a1.addScore(-1);
    $a2.addScore(-1);
    System.out.println("\nRule 4: Anotations have same lipid type, same DBs, more carbons, lower RT."
            + "\nAdd a score of -1 to both anotations:\n - " + $a1 + "\n - " + $a2);
end

rule "Rule 5: Same lipid type, fewer double bonds, same carbons, lower retention time"
when
    $a1 : /annotations [
        $lipidType1 : lipid.getLipidType(),
        $doubleBondCount1 : lipid.getDoubleBondsCount(),
        $carbonCount1 : lipid.getCarbonCount(),
        $retentionTime1 : rtMin
    ]
    $a2 : /annotations [
        this != $a1,
        lipid.getLipidType() == $lipidType1,
        lipid.getDoubleBondsCount() > $doubleBondCount1,
        lipid.getCarbonCount() == $carbonCount1,
        rtMin > $retentionTime1
    ]
then
    $a1.addScore(-1);
    $a2.addScore(-1);
    System.out.println("\nRule 5: Anotations have same lipid type, fewer DBs, same carbons, lower RT."
            + "\nAdd a score of -1 to both anotations:\n - " + $a1 + "\n - " + $a2);
end

rule "Rule 6: Different lipid type (higher type rank), same double bonds, same carbons, lower retention time"
when
     $a1 : /annotations [
         $lipidType1 : lipid.getLipidType(),
         $doubleBondCount1 : lipid.getDoubleBondsCount(),
         $carbonCount1 : lipid.getCarbonCount(),
         $retentionTime1 : rtMin
     ]
     $a2 : /annotations [
         this != $a1,
         lipid.getLipidType() != $lipidType1,
         lipid.getDoubleBondsCount() == $doubleBondCount1,
         lipid.getCarbonCount() == $carbonCount1,
         rtMin > $retentionTime1
     ]
     eval($a1.getLipid().getLipidTypeRank() > $a2.getLipid().getLipidTypeRank())
then
    $a1.addScore(-1);
    $a2.addScore(-1);
    System.out.println("\nRule 6: Anotations have different lipid type (lower rank), same DBs, same carbons, lower RT."
            + "\nAdd a score of -1 to both anotations:\n - " + $a1 + "\n - " + $a2);
end
